stages:
  - deploy

variables:
  APP_NAME_STAGING: levumi2-staging
  APP_NAME_PROD: levumi2-prod

deploy_staging:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: staging
    url: https://staging.levumi.de/
  only:
    - staging
  script:
    - git-push ssh://dokku@ruapehu.informatik.uni-kiel.de:22/$APP_NAME_STAGING --force
# TODO adapt to deployment on ddi machine
#deploy_production:
#  image: ilyasemenov/gitlab-ci-git-push
#  stage: deploy
#  environment:
#    name: production
#    url: https://levumi.de/
#  only:
#    - master
#  script:
#    - git-push ssh://dokku@ruapehu.informatik.uni-kiel.de:22/$APP_NAME_PROD
