version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid; rails s -b '0.0.0.0' -p 3000"
    depends_on:
      - vite
    volumes:
      - ./:/usr/src/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    tmpfs: /app/tmp
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: vite
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
  vite:
    build: .
    command: bash -c "vite dev"
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - '3036:3036'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/app/node_modules
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: levumi2_dev
      MYSQL_USER: levumi2
      MYSQL_PASSWORD: 2imuvel
    ports:
      - '3307:3306'
    volumes:
      - ./levumi2.sql:/docker-entrypoint-initdb.d/levumi2.sql
  redis:
    image: redis
    volumes:
      - redis_data:/data
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  bundle:
  pg_data:
  redis_data:
